### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by matthiasa4** [googleapis/java-recommendations-ai#220]
When trying to use the example code provided in the [documentation](https://googleapis.dev/java/google-cloud-recommendations-ai/latest/index.html) to speak to the Recommendation AI API through the Java client to create CatalogItems, I run into the above Exception. 

Full stack trace:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkArgument(boolean, java.lang.String, char, java.lang.Object)'
        at io.grpc.Metadata$Key.validateName(Metadata.java:742)
        at io.grpc.Metadata$Key.<init>(Metadata.java:750)
        at io.grpc.Metadata$Key.<init>(Metadata.java:668)
        at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:959)
        at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:954)
        at io.grpc.Metadata$Key.of(Metadata.java:705)
        at io.grpc.Metadata$Key.of(Metadata.java:701)
        at com.google.api.gax.grpc.GrpcHeaderInterceptor.<init>(GrpcHeaderInterceptor.java:60)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:239)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1600(InstantiatingGrpcChannelProvider.java:71)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:210)
        at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:217)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:200)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:169)
        at com.google.cloud.recommendationengine.v1beta1.stub.GrpcCatalogServiceStub.create(GrpcCatalogServiceStub.java:142)
        at com.google.cloud.recommendationengine.v1beta1.stub.CatalogServiceStubSettings.createStub(CatalogServiceStubSettings.java:163)
        at com.google.cloud.recommendationengine.v1beta1.CatalogServiceClient.<init>(CatalogServiceClient.java:146)
        at com.google.cloud.recommendationengine.v1beta1.CatalogServiceClient.create(CatalogServiceClient.java:127)
        at com.google.cloud.recommendationengine.v1beta1.CatalogServiceClient.create(CatalogServiceClient.java:118)
        at com.mbae.RecommendationEngineApiSample.main(RecommendationEngineApiSample.java:50)
```

Relevant code:
```
import com.google.cloud.recommendationengine.v1beta1.CatalogServiceClient;

public class RecommendationEngineApiSample {
    public static void main(String[] args) throws IOException {
        try (CatalogServiceClient catalogServiceClient = CatalogServiceClient.create()) {
            CatalogName parent = CatalogName.of("[PROJECT]", "[LOCATION]", "[CATALOG]");
            CatalogItem catalogItem = CatalogItem.newBuilder().build();
            CatalogItem response = catalogServiceClient.createCatalogItem(parent, catalogItem);
        }
    }
}
```

Am I missing something? Any help would be appreciated.

**Comment by chingor13** [comment]
This looks like you're missing the guava dependency. If you're using Maven or Gradle this dependency should be automatically pulled (unless it's being explicitly excluded).

**Comment by matthiasa4** [comment]
Running `mvn dependency:tree` as per your suggestion returns the below ones relevant for `guava`:

```
[INFO] |  \- com.google.guava:guava-jdk5:jar:17.0:compile
[INFO]    +- com.google.guava:guava:jar:30.0-android:compile
[INFO]    +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO]    +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
```

But still the same issue.
Shall I try explicitly adding it to my `pom`?

**Comment by suztomo** [comment]
Wrong version of Guava cases such dependency conflicts. Closing for obsolete.
