### ISSUE TITLE
Purge user events fails

### ISSUE THREAD

**Issue by rotilho** [googleapis/java-recommendations-ai#289]
Stacktrace

```
2021-03-26 12:01:43.317 ERROR 230317 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'importerStarter': Invocation of init method failed; nested exception is java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Resource name purge-userevents-default_catalog-default_event_store-14747732420306592688 cannot be parsed. Resource name prefix must be of the format 'v1beta1/projects/<Your_Project_Number>/locations/*/catalogs/*/eventStores/*/operations/*'. Make sure to pass Project Number instead of Project ID. To get the Project number, refer to https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:63) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.4.3.jar:2.4.3]
	at com.bux.recommendation.importer.security.SecurityImpoterApplicationKt.main(SecurityImpoterApplication.kt:13) ~[classes/:na]
Caused by: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Resource name purge-userevents-default_catalog-default_event_store-14747732420306592688 cannot be parsed. Resource name prefix must be of the format 'v1beta1/projects/<Your_Project_Number>/locations/*/catalogs/*/eventStores/*/operations/*'. Make sure to pass Project Number instead of Project ID. To get the Project number, refer to https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566) ~[guava-30.1-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547) ~[guava-30.1-android.jar:na]
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:86) ~[guava-30.1-android.jar:na]
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62) ~[guava-30.1-android.jar:na]
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:127) ~[gax-1.62.0.jar:1.62.0]
	at com.bux.recommendation.importer.security.Importer.import(Importer.kt:39) ~[classes/:na]
	at com.bux.recommendation.importer.security.Importer$$FastClassBySpringCGLIB$$8f0b63c3.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.4.jar:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.4.jar:5.3.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.4.jar:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.4.jar:5.3.4]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.4.jar:5.3.4]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.4.jar:5.3.4]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.4.jar:5.3.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.4.jar:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.4.jar:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.4.jar:5.3.4]
	at com.bux.recommendation.importer.security.Importer$$EnhancerBySpringCGLIB$$133af86e.import(<generated>) ~[classes/:na]
	at com.bux.recommendation.importer.security.ImporterStarter.start(ImporterStarter.kt:11) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.4.jar:5.3.4]
	... 19 common frames omitted
Caused by: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Resource name purge-userevents-default_catalog-default_event_store-14747732420306592688 cannot be parsed. Resource name prefix must be of the format 'v1beta1/projects/<Your_Project_Number>/locations/*/catalogs/*/eventStores/*/operations/*'. Make sure to pass Project Number instead of Project ID. To get the Project number, refer to https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49) ~[gax-1.62.0.jar:1.62.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72) ~[gax-grpc-1.62.0.jar:1.62.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60) ~[gax-grpc-1.62.0.jar:1.62.0]
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) ~[gax-grpc-1.62.0.jar:1.62.0]
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) ~[api-common-1.10.1.jar:na]
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1041) ~[guava-30.1-android.jar:na]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-30.1-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1215) ~[guava-30.1-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983) ~[guava-30.1-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771) ~[guava-30.1-android.jar:na]
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563) ~[grpc-stub-1.36.0.jar:1.36.0]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533) ~[grpc-stub-1.36.0.jar:1.36.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) ~[grpc-core-1.36.0.jar:1.36.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) ~[grpc-core-1.36.0.jar:1.36.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) ~[grpc-core-1.36.0.jar:1.36.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) ~[grpc-core-1.36.0.jar:1.36.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.36.0.jar:1.36.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.36.0.jar:1.36.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Resource name purge-userevents-default_catalog-default_event_store-14747732420306592688 cannot be parsed. Resource name prefix must be of the format 'v1beta1/projects/<Your_Project_Number>/locations/*/catalogs/*/eventStores/*/operations/*'. Make sure to pass Project Number instead of Project ID. To get the Project number, refer to https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects
	at io.grpc.Status.asRuntimeException(Status.java:535) ~[grpc-api-1.36.0.jar:1.36.0]
	... 13 common frames omitted


Process finished with exit code 1

```

Code
```
        val eventStore = EventStoreName.of("[PROJECT]", "global", "default_catalog", "default_event_store")

        UserEventServiceClient.create(userEventServiceSettings).use { client ->
            val response = client.purgeUserEventsAsync(eventStore, "eventType=add-to-cart", true).get()
            println(response)
        }
```

Same eventStore works fine when used to list events.

**Comment by rotilho** [comment]
May be related to https://github.com/googleapis/python-recommendations-ai/issues/12

**Comment by Neenu1995** [comment]
Hi @rotilho 

Thanks for reaching out. This is an issue in Recommendations AI v1beta1 client library due to the LRO names not using fully qualified names. Fixing it will break existing v1beta1 customers. However. it has been fixed in [V2 client libraries](https://cloud.google.com/retail/docs/reference/libraries). Hope this helps.
